<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "datamints_top"
 *
 * Auto generated by Extension Builder 2022-04-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'datamints Top',
    'description' => 'Adds a button to jump to the top of a page',
    'category' => 'misc',
    'author' => 'Mark Weisgerber',
    'author_email' => 'm.weisgerber@datamints.com',
    'state' => 'stable',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '7.0.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
